[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[functions."saveTotalAsset"]
  schedule = "30 20 * * *" # ساعت ۰۰:۰۰ ایران

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
