[build]
command = "npm run build"

[functions]
directory = "netlify/functions"

[functions."saveTotalAsset"]
  schedule = "30 20 * * *" # ساعت ۰۰:۰۰ ایران

[[plugins]]
  package = "@netlify/plugin-nextjs"
